### ISSUE TITLE
Removing YADR

### ISSUE THREAD

**Issue by ghost** [skwp/dotfiles#101]
I'm a bit of a command line newb & want to revert yadr. I read in the docs it mentions it will not over ride my old files. Can someone please tell me what commands I need to run to do that please?

Thanks.

**Comment by RazzyP** [comment]
It looks like your dotfiles are still symlinked to their yadr equivalents in the now removed .yadr file. I don't know why they're still showing up. Did you try renaming the .backup files as listed above? 

```bash
mv .vimrc.backup .vimrc
```

**Comment by jby** [comment]
Well .vim and .vimrc were moved out of the way in the install process, and symbolic links were created in their place. This means you won't be able to
```bash
mv .vimrc.backup .vimrc
```
without first doing
```bash
rm .vimrc .vim
```
So, if .vim and .vimrc are symbolic links that point into "cyberspace" instead of to an actual file, they have to be removed before you can move your backup-files back into place.

**Comment by scottyseus** [comment]
@skwp  `rm -rf ~/.yadr` worked perfectly cleanly for me. YADR just wasn't for me, but I appreciate such an easy removal.

**Comment by tiagoramos92** [comment]
I think this dotfiles is great but it brings me some problems with my co-workers that use bash Is there any dotfiles like these for bash shell?
