### ISSUE TITLE
zprezto override not registering behavior

### ISSUE THREAD

**Issue by ianks** [skwp/dotfiles#542]
Adding:  `zstyle ':prezto:module:tmux:auto-start' local 'yes'` to `~/.zpreztorc` does nothing. 

Something fishy is going on it seems.

**Comment by lfilho** [comment]
@ianks Is this still an issue? Feel free to close this issue if not.

Otherwise please provide more info... zsh, tmux and iterm versions...

Did you check https://gitlab.com/gnachman/iterm2/wikis/TmuxIntegration ?

I also noticed that the example line in https://github.com/skwp/dotfiles/blob/master/zsh/prezto-override/zpreztorc#L134 has a different syntax... Not sure if it plays an important role (probably not).

**Comment by skwp** [comment]
This is from 2014, closing
