### ISSUE TITLE
'bundle' deprecated in Vundle

### ISSUE THREAD

**Issue by johngb** [skwp/dotfiles#561]
Vundle has [deprecated the 'bundle' command](https://github.com/gmarik/Vundle.vim/blob/v0.10.2/doc/vundle.txt#L372-L396) in favour of 'package'.

While this isn't a big deal, it would probably be a good idea to move over as well.

**Comment by lfilho** [comment]
It's indeed deprecated (although it's been almost 3 years now). And in their docs they say the new `Plugin` command has new features (such as comments) and maybe more in the future.

But this has hit master and the reverted (https://github.com/skwp/dotfiles/commit/3b8120e9d4ca7eb2a81199a1412f937b7eeb95ec) due to problems when upgrading YADR (this repo has many followers...). So I guess we could close this issue now until we find a way of improving things with better retro compatibility or devise a strategy to make a new bold release with breaking changes... @skwp ?

**Comment by skwp** [comment]
Yeah we need backward compatibility. Also, if it works it's not broken. Not clear the benefits of upgrading at this point. If anything we should look at other plugin systems that might be faster
