### ISSUE TITLE
error: could not lock config file .git/config: Permission denied

### ISSUE THREAD

**Issue by westhechiang** [skwp/dotfiles#675]
I went to ~/.yadr to update and was greeted with the following error message `error: could not lock config file .git/config: Permission denied`

**Comment by scottenriquez** [comment]
I got this issue with the most recent version.

**Comment by CLarmour** [comment]
Hey @scottenriquez could you elaborate for me? What did you do with chmod to fix?

**Comment by scottenriquez** [comment]
Hey, @CLarmour,

Sorry for the late reply. If I remember correctly, I simply used the following command: `chmod 777 ~/.yadr/.git/config` to grant read, write, and execute to everyone. Depending on your setup, you may want to lock down the permissions a bit more. Also note that this is assuming that YADR has been installed in your home directory. If you used the `install.sh` script, you should be good to go.

**Comment by CLarmour** [comment]
Hey no problem, thanks for the reply!

So it should have read, write, AND execute under permissions? I recall in my adventures in keychain access, only read + write were allowed to (me), system, and everyone.
I'll definitely try that command, thanks!

Sent from my iPhone

On Jan 28, 2017, at 17:19, Scottie Enriquez <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey, @CLarmour<https://github.com/CLarmour>,

Sorry for the late reply. If I remember correctly, I simply used the following command: chmod 777 ~/.yadr/.git/config to grant read, write, and execute to everyone. Depending on your setup, you may want to lock down the permissions a bit more. Also note that this is assuming that YADR has been installed in your home directory. If you used the install.sh script, you should be good to go.

-

**Comment by lfilho** [comment]
I'm assuming some other tool reading/writing to that file (say Git Tower or whatever) changed the file permissions...

We didn't have more complaints about this and it's been a while, so I'm taking the liberty of closing this issue, ok? Feel free to reopen it if needed

**Comment by Axelay-Prime** [comment]
Corporate security policy prohibits writing to the "H:" path, directly.  I have an "H:\$user\" directory that I can write to, however, the global (and GPO enforced) home directory variable is incomplete, and points to "H:" directly.

Because I have found no reasonably sane method to actually adjust the default location that the git for windows tool(s) use (I've tried 3 different packages, but they all seem to tie back to the same base project code).  So I'm 'stuck'.

error: could not lock config file H://.gitconfig: Permission denied

**Comment by Axelay-Prime** [comment]
I wasn't able to create a local .gitconfig, since the windows GPO doesn't allow viewing hidden files, or setting the extensions of files.
But I was able to use winSCP to copy my linux .gitconfig directly in to the local repo on windows and now I'm able to use my direct rubymine integration, and skip using the github desktop for windows interface.  (though I am pointing rubymine to the git executable that comes with github desktop)

**Comment by danisacipo** [comment]
> 

hola, pudiste solucionar ese problema? yo tengo el mismo...
