### ISSUE TITLE
Zsh Plugins

### ISSUE THREAD

**Issue by fayimora** [skwp/dotfiles#722]
I couldn't find anything on how zsh plugins are managed(where they live and how to install them). Any ideas? For instance, what should I do to get [this plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/golang/golang.plugin.zsh)

**Comment by lfilho** [comment]
Isn't the `zsh` folder in the rood directory what you're after?

If the desired plugin is not there (or part of prezto), then you can either submit a PR (since this repo's is not targeted at Go language, it probably won't be merged by the maintainer) or you could fork the repo to add the plugin to yours...

Feel free to close the issue, cheers

**Comment by lfilho** [comment]
Closing this one due to lack of response from original author. Feel free to reopen it if you judge necessary.
