### ISSUE TITLE
vim suspended

### ISSUE THREAD

**Issue by Lumuy** [skwp/dotfiles#744]
In my ruby file **service.rb**, if I write

             "#{}/" 

after '/'  input, vim get suspended.

My system is Ubuntu.

**Comment by lfilho** [comment]
Tested on MacVim and NeoVim (both under OSX) and couldn't reproduce the issue.

We need more confirmations from Linux users and then someone should provide a fix for us. The repo is primarily aimed at OSX as its what its maintainers use. We need more Linux users testing and contributing to this repo in order to support it. Otherwise I'm afraid there's not much else we could do.

So... Any other linux users confirm this?

**Comment by lfilho** [comment]
Maybe related to #742 ?

**Comment by lfilho** [comment]
Maybe related to https://github.com/skwp/dotfiles/issues/727#issuecomment-277459325 ? @Lumuy could you please check?

**Comment by lfilho** [comment]
ping @Lumuy

**Comment by Lumuy** [comment]
@lfilho
 I uninstall vim (with lua), then install vim (without lua), then this problem disappear. But another question is how to install vim with lua.  Installing vim(with lua) from source code with system ruby cause the same problem.

**Comment by lfilho** [comment]
I'm not sure, @Lumuy, as I have never had this problem. The other users of this repo seem to also not experience this (nobody else pointed this out so far). I must be some weird thing going on with you system.

If you follow the troubleshooting steps mentioned in the readme, than I personally don't know how else to help you...

Feel free to reopen this issue if you find a way to provide us a set of steps to reproduce this error, that would be great. Otherwise, our hands are tied... Thanks and good luck
