### ISSUE TITLE
Javascript files syntax highlighting and indenting issues

### ISSUE THREAD

**Issue by westhechiang** [skwp/dotfiles#753]
Hey there, great job on this dotfile repo! I was wondering if anyone else was having any issues with their javascript syntax highlighting and indenting; take a look at the .gif below?

![js-syntax](https://cloud.githubusercontent.com/assets/7388796/26514646/fdf0ca30-4227-11e7-8213-1a7ba1fe617c.gif)

Shouldn't the args in the function have coloring and when I hit return after the opening curly, shouldn't my cursor auto-indent 2 spaces and the closing brace be on the 3rd line?

I'm on OSX El Capitan 10.11.6 with a fresh install of YADR.

**Comment by westhechiang** [comment]
I just tried removing mxw/vim-jsx per https://github.com/skwp/dotfiles/pull/729 my syntax highlighting and indentation problems still persist.

**Comment by lfilho** [comment]
I think the indenting you're looking for is not provided with the current set of plugins we have. I might be wrong. Try using AutoPairs (instead of delimitMate).

As for the syntax, I personally don't use Solarized so I don't know how it should look. Are you sure this is not intended? Was this working differently for you before?

I'm using a different colorscheme but it also doesn't color the args:
![image](https://cloud.githubusercontent.com/assets/282756/26553183/d5a568fa-448a-11e7-8b5a-e6dbe3d28128.png)

**Comment by westhechiang** [comment]
Ah, I see. Yeah I don't mind the args not having a different color scheme; let me give AutoPairs a try, @lfilho

**Comment by westhechiang** [comment]
As a follow-up, I've installed AutoPairs per @lfilho's suggestion and my javascript is now auto-indenting as expected.

Still not sure if this is how we expect to resolve the indentation issue for JS though.

**Comment by lfilho** [comment]
I believe the standards libs for indentation don't mean to do AUTO indentation. Rather fix indendations when, for example, we invoke `==` on a line. I might be wrong... Best way to make sure is to read the documentation on each plugin to make sure...

So if you don't object, I'm closing this issue, ok? Cheers
