### ISSUE TITLE
can't use 'tab' key

### ISSUE THREAD

**Issue by yanxueqing621** [skwp/dotfiles#762]
the 'tab' key don't function,  for example:   when I write a file in vim as follow
```
a  1    1
b  2    2
c  3    3
```
then run `cut -f 1`  in cmd of linux, I will get the result of whole file, it seems like that there is no 'tab' in every line;

Is any one have good idea to solve this problem?

**Comment by lfilho** [comment]
That's probably because of https://github.com/skwp/dotfiles/blob/f721304a2c45fc7e035555ed51b44d71e4e59da2/vimrc#L65 (check the documentation at `:h softtabstop`).

If you need to actually insert a tab character instead of expanding it to spaces, you need to overwrite that (via the `after` file, or a specific plugin, or autocommands for a specific filetype, etc).

But unless it's a filetype that **demands** actual tab chars, nowadays it's pretty much an industry standard not to use actual tabs in the name of consistency, as they vary in width from editor to editor, from env to env...
