### ISSUE TITLE
vim errors on fresh install

### ISSUE THREAD

**Issue by brebaje** [skwp/dotfiles#808]
Fresh installation on macOS Mojave.
When opening a file with vim I get the following errors:

```
Error detected while processing function <SNR>239_buffer_type:
line    1:
E605: Exception not caught: fugitive: Removed in favor of b:fugitive_type (or ideally avoid entirely)
Error detected while processing function FugitiveDetect:
line   11:
E171: Missing :endif
```

I do not get these errors if I just open vim alone though

Any ideas? I've tried reinstalling macvim without luck

**Comment by steezeburger** [comment]
Same thing is happening to me as well, but it's when loading the one from my own ~/.vim, not ~/.yadr/vim.

Does yadr put plugins in my own ~/.vim/bundles or did something else do this? Macvim maybe?

**Comment by pablobender** [comment]
The same for me... not on fresh install but after `rake update`.

The problem is being caused by tpope/vim-fugitive plugin. More precisely, it began in the commit https://github.com/tpope/vim-fugitive/commit/d41dee9c0b0cd2ffc364f2784d764b76e43ae057

vim-fugitive tries to detect if the file being loaded is in a git repository. This is why the problem not happens when opening the vim alone.

So if you `cd ~/.vim/bundle/vim-fugitive` and `git checkout d41dee9~`  the problem will stop until you update the vim plugins again.

@tope is working hard this days, many git pushes... I hope this problem will be solved soon.

**Comment by pablobender** [comment]
The same for me... not on fresh install but after `rake update`.

The problem is being caused by tpope/vim-fugitive plugin. More precisely, it began in the commit https://github.com/tpope/vim-fugitive/commit/d41dee9c0b0cd2ffc364f2784d764b76e43ae057

vim-fugitive tries to detect if the file being loaded is in a git repository. This is why the problem not happens when opening the vim alone.

So if you `cd ~/.vim/bundle/vim-fugitive` and `git checkout d41dee9~`  the problem will stop until you update the vim plugins again.

@tpope is working hard this days, many git pushes... I hope this problem will be solved soon.

**Comment by pablobender** [comment]
You're completely right @tpope. (nothing like the look of an expert).

Unfortunately I was looking inside the vim-fugitive and didn't see this map so obvious. 😞 
It makes perfect sense.

Paleatively, removing this [this map](https://github.com/skwp/dotfiles/blob/50767f29218ffcd19521d543c5a06820fb78101d/vim/settings/vim-fugitive.vim#L6-L8) the problem will not happen.

Also, I have not yet figured out how to change this statement to keep the mapping `..`. But as I've never used it, removing this `autocmd` block is fine for me, and I can keep my environment up to date. 😍 

Thanks a lot.

**Comment by FLemon** [comment]
so...what's the best way to walkaround this error?
 - remove vim-fugitive
 - downgrade vim-fugitive
 - override/unmap the fugitive in vimrc(or somehow)
 - others?(what and how)

can you suggest one of the above?
@tpope

**Comment by tpope** [comment]
I would suggest removing the map entirely or changing the function call to `get(b:, 'fugitive_type', '')`.

**Comment by brebaje** [comment]
Sorry for the delay, confirmed working, thanks a lot
