### ISSUE TITLE
FUNCNEST error when using .zsh.after to configure starship prompt

### ISSUE THREAD

**Issue by gmaghera** [skwp/dotfiles#875]
This may not be a YADR issue per se, but it is related, and I am hoping someone can set me in the right direction. 

I started using https://starship.rs/ for a prompt. If I configure it via a `~/.zsh.after/starship.zsh` file, every time I use escape to go into normal vi mode there is a FUNCNEST error.

`~/.zsh.after/starship.zsh`
```
eval "$(starship init zsh)"
```

And the error:
```
❯ lsls asdfa
starship_zle-keymap-select-wrapped:1: maximum nested function level reached; increase FUNCNEST?
```

Here is the interesting part. If I remove that configuration file, and open a new terminal window or tab, and then paste the command `eval "$(starship init zsh)"`, everything works just fine. There seems to be some incompatibility between the (very handy and portable) way YADR stores zsh customizations and what starship wants to do.

Thank you!

**Comment by gmaghera** [comment]
Closing since this was just a fishing expedition to start with, unlikely to be a YADR issue.

**Comment by cgoliver** [comment]
Just a note. I am also experiencing this issue.

**Comment by dukeEllington32** [comment]
@gmaghera , did you ever find a solution to this? I'm having the same issue.

**Comment by Opposite34** [comment]
I know this is a while ago, but this happens when you `eval "$(starship init zsh)"` many times. So, if you resource your zsh without exiting the shell (for example, after changing some config) it will happen. 

I don't use YADR. I just happened to come across this thread after my starship having this problem, but if this happens without resourcing (on a freshly opened terminal), then something maybe wrong with the YADR configurations.
