### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by pdehlke** [skwp/dotfiles#876]
Nothing has been committed and no PR has been merged in nearly a year...

**Comment by joneserick** [comment]
I would like to know too...

**Comment by lfilho** [comment]
I haven’t seen @skwp around here in a while and since I maintain my own
fork for a few years now, i only help here with more straightforward
stuff (things that don’t require @skwp decision/input), or things that
still overlap with my own fork… 

On March 18, 2022, GitHub ***@***.***> wrote:
> I would like to know too...
>

—
Reply to this email directly, view it on GitHub
<https://github.com/skwp/dotfiles/issues/876#issuecomment-1072381036>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AACFBBC6TOY253IO5PBRD6TVAR36TANCNFSM5M5ZNO4A>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>
